version: '3.8'
services:
  api:
    container_name: langchain-financial-reporting-api
    image: langchain-financial-reporting-api:${TAG:-latest}
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - POLYGON_API_ENDPOINT=${POLYGON_API_ENDPOINT}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - PORT=${PORT}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - POOL_MANAGEMENT_ENDPOINT=${POOL_MANAGEMENT_ENDPOINT}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - APP_CLIENT_ID=${APP_CLIENT_ID}
      - OPENAPI_CLIENT_ID=${OPENAPI_CLIENT_ID}
      - CORS_URL=${CORS_URL}
      - ENVIRONMENT=${ENVIRONMENT}
  chat:
    container_name: langchain-financial-reporting-chat
    image: langchain-financial-reporting-chat:${TAG:-latest}
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - ${CHAT_PORT}:${CHAT_PORT}
    env_file:
      - .env
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
      - APP_TENANT_ID=${APP_TENANT_ID}
      - AUTHORIZE_ENDPOINT=${AUTHORIZE_ENDPOINT}
      - TOKEN_ENDPOINT=${TOKEN_ENDPOINT}
      - APP_CLIENT_ID=${APP_CLIENT_ID}
      - API_CLIENT_ID=${API_CLIENT_ID}
      - APP_CLIENT_SECRET=${APP_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - ICON_URL=${REDIRECT_URI}
      - ENVIRONMENT=${ENVIRONMENT}