name: Build, Test and Deploy to Azure
on: 
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  development-build:
    environment: DEVELOPMENT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - directory: backend
            container_name: financial-reporting-api
          - directory: frontend
            container_name: financial-reporting-chat
          - directory: experimental
            container_name: financial-reporting-experimental
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@main
      
    - name: Azure CLI Login
      uses: Azure/login@v2.2.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: Azure/cli@v2.1.0
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Build the API Image using Azure Container registry
      uses: Azure/cli@v2.1.0
      with:
        azcliversion: latest
        inlineScript: |
          cd ${{ matrix.directory}} && az acr build -r ${{ secrets.AZURE_CONTAINER_REGIStRY }} -t financial-advisor/langchain/${{ matrix.container_name }}:${{ github.sha }} --file Dockerfile .
  
  development-deployment:
    environment: DEVELOPMENT
    runs-on: ubuntu-latest
    needs: development-build
    steps:
      - name: Azure CLI Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Azure CLI Script
        uses: Azure/cli@v2.1.0
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: Deploy the API Image to Azure Container App
        uses: Azure/cli@v2.1.0
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp revision copy -n  ${{ secrets.FINANCIAL_ADVISOR_API_RESOURCE_NAME }} -g ${{ secrets.FINANCIAL_ADVISOR_RESOURCE_GROUP }} -i ${{ secrets.AZURE_CONTAINER_REGIStRY }}.azurecr.io/financial-advisor/langchain/financial-reporting-api:${{ github.sha }}
      
      - name: Deploy the Chat Image to Azure Container Apps 
        uses: Azure/cli@v2.1.0
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp revision copy -n  ${{ secrets.FINANCIAL_ADVISOR_CHAT_RESOURCE_NAME }} -g ${{ secrets.FINANCIAL_ADVISOR_RESOURCE_GROUP }} -i ${{ secrets.AZURE_CONTAINER_REGIStRY }}.azurecr.io/financial-advisor/langchain/financial-reporting-chat:${{ github.sha }}
        
