name: Build, Test and Deploy to Azure
on: 
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  development:
    environment: DEVELOPMENT
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@main
      
    - name: Azure CLI Login
      uses: Azure/login@v2.2.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: Azure/cli@v2.1.0
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Build the API Image using Azure Container registry
      uses: Azure/cli@v2.1.0
      with:
        azcliversion: latest
        inlineScript: |
          cd backend && az acr build -r ${{ secrets.AZURE_CONTAINER_REGIStRY }} -t financial-advisor/langchain/financial-reporting-api:${{ github.sha }} --file Dockerfile .

    - name: Build the Chat Image using Azure Container Registry
      uses: Azure/cli@v2.1.0
      with:
        azcliversion: latest
        inlineScript: |
          cd frontend && az acr build -r ${{ secrets.AZURE_CONTAINER_REGIStRY }} -t financial-advisor/langchain/financial-reporting-chat:${{ github.sha }} --file Dockerfile .

    - name: Build the Experimental Image using Azure Container Registry
      uses: Azure/cli@v2.1.0
      with:
        azcliversion: latest
        inlineScript: |
          cd experimental && az acr build -r ${{ secrets.AZURE_CONTAINER_REGIStRY }} -t financial-advisor/langchain/financial-reporting-experimental:${{ github.sha }} --file Dockerfile .
